swiftmailer:
    # transport: "%mailer_transport%"
    # host:      "%mailer_host%"
    # username:  "%mailer_user%"
    # password:  "%mailer_password%"
    # port:      "%mailer_port%"
    # auth_mode: "%mailer_auth_mode%"
    # spool:     { type: memory }
