twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        myd_version: "%myd_version%"
        locales: '%fallbacks%'
    form_theme: ['bootstrap_4_layout.html.twig']    