Myddleware\RegleBundle\Entity\ConnectorParam:
    properties:
        value:
            - Length:
                max: 200
                maxMessage: The values of the connector params must be maximum 200 characters
        