# This file allows you to register your custom classes.

services:
  _defaults:
    autowire: true      
    autoconfigure: true 
    public: false      

# Here you must declare your custom classes and what classes they decorates using the syntax below.
# For example, if I've created a woocommercecustom.php file in src/Custom/Solutions,
# I declare here that this class decorates the default woocommerce class. 
# Each time you've made a modification of this file, please ensure you clear your cache using
# php bin/console cache:clear     
# You must use the same syntax for each custom class you create. For further info : 
# https://symfony.com/doc/4.4/service_container/service_decoration.html 

  # App\Custom\Solutions\woocommercecustom:
  #     decorates: App\Solutions\woocommerce
  #     decoration_on_invalid: ignore
  #     decoration_priority: 5

  # App\Custom\Solutions\wordpresscustom:
  #     decorates: App\Solutions\wordpress
  #     decoration_on_invalid: ignore
  #     decoration_priority: 1

  App\Custom\Premium\Solutions\mysqlpremium:
    decorates: App\Solutions\mysql
    decoration_on_invalid: ignore
    decoration_priority: 1

  App\Custom\Solutions\mysqlcustom:
    decorates: App\Custom\Premium\Solutions\mysqlpremium
    decoration_on_invalid: ignore
    decoration_priority: 1
    
  App\Custom\Premium\Manager\DocumentManagerPremium:
    decorates: App\Manager\DocumentManager
    decoration_on_invalid: ignore
    decoration_priority: 1
    
  App\Custom\Premium\Manager\ToolsManagerPremium:
    decorates: App\Manager\ToolsManager
    decoration_on_invalid: ignore
    decoration_priority: 1